Hotfix of unused variable compile error.
Hotfix of unused variable compile error due to left over code from @KisekiHirakawa. Reported by @marcuspirron.
```
newton-irPass-dimensionalMatrixKernelPrinter.c:374:10: error: unused
variable 'numberOfConstPi' [-Werror,-Wunused-variable]
                                        int numberOfConstPi = 0;
                                            ^
1 error generated.
```