Two functions for OpenCL are deprecated: first deprecated in macOS 10.14
Both `gcl_create_dispatch_queue` and `gcl_get_device_id_with_dispatch_queue` are deprecated: first deprecated in macOS 10.14 (Mojave)

Error report as follows:
```
common-utils.c:244:27: error: 'gcl_create_dispatch_queue' is deprecated: first deprecated in macOS 10.14 - (Define CL_SILENCE_DEPRECATION to hide this warning) [-Werror,-Wdeprecated-declarations]
        dispatch_queue_t queue = gcl_create_dispatch_queue(CL_DEVICE_TYPE_GPU, NULL);
                                 ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenCL.framework/Headers/gcl.h:85:36: note: 'gcl_create_dispatch_queue' has been explicitly marked deprecated here
extern dispatch_queue_t __nullable gcl_create_dispatch_queue(cl_queue_flags flags,
                                   ^
common-utils.c:247:11: error: 'gcl_create_dispatch_queue' is deprecated: first deprecated in macOS 10.14 - (Define CL_SILENCE_DEPRECATION to hide this warning) [-Werror,-Wdeprecated-declarations]
                queue = gcl_create_dispatch_queue(CL_DEVICE_TYPE_CPU, NULL);
                        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenCL.framework/Headers/gcl.h:85:36: note: 'gcl_create_dispatch_queue' has been explicitly marked deprecated here
extern dispatch_queue_t __nullable gcl_create_dispatch_queue(cl_queue_flags flags,
                                   ^
common-utils.c:251:21: error: 'gcl_get_device_id_with_dispatch_queue' is deprecated: first deprecated in macOS 10.14 - (Define CL_SILENCE_DEPRECATION to hide this warning) [-Werror,-Wdeprecated-declarations]
        cl_device_id    gpu = gcl_get_device_id_with_dispatch_queue(queue);
                              ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenCL.framework/Headers/gcl.h:199:32: note: 'gcl_get_device_id_with_dispatch_queue' has been explicitly marked
      deprecated here
extern cl_device_id __nullable gcl_get_device_id_with_dispatch_queue(dispatch_queue_t __nonnull queue) GCL_API_SUFFIX__VERSION_1_1 CL_DEPRECATED(10.7, 10.14);
                               ^
common-utils.c:252:2: error: 'clGetDeviceInfo' is deprecated: first deprecated in macOS 10.14 - (Define CL_SILENCE_DEPRECATION to hide this warning) [-Werror,-Wdeprecated-declarations]
        clGetDeviceInfo(gpu, CL_DEVICE_NAME, 128, name, NULL);
        ^
/Applications/Xcode.app/Contents/Developer/Platforms/MacOSX.platform/Developer/SDKs/MacOSX10.14.sdk/System/Library/Frameworks/OpenCL.framework/Headers/cl.h:591:1: note: 'clGetDeviceInfo' has been explicitly marked deprecated here
clGetDeviceInfo(cl_device_id    /* device */,
^
```

Addresses #358.